//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petshop2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvz1
    {
        public int id { get; set; }
        public int art { get; set; }
        public int city { get; set; }
        public int street { get; set; }
        public Nullable<int> house { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Street Street1 { get; set; }
    }
}
